on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: choice
        required: true
        options:
          - JonDotsoy/q-project
        description: "describe the name of project to make the spec file"

jobs:
  das:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - id: refresh
        run: bun scripts/refresh.ts ${{ inputs.repo_name }}
        env:
            GH_TOKEN: ${{ github.token }}
      - run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
        if: steps.refresh.outputs.updated == 'true'
      - run: |
          git add ${{ steps.refresh.outputs.output }}
          git commit -m "chore: ${{ inputs.repo_name }} ${{ steps.refresh.outputs.release_tag_name }}"
          git push